edit-livecd: add new attribute compress_type
to avoid:
AttributeError: 'LiveImageEditor' object has no attribute 'compress_type'

LiveImageEditor is a special subclass of LiveImageCreator
which does not use parent's initializer so we must set all attributes.

Signed-off-by: Alan Pevec <apevec@redhat.com>